[mgroup.0]
name = "XY-drive"
port_number = 32
port_orientation = "E"
axes.ip = ["192.168.0.70", "192.168.0.80"]
axes.units = ["cm", "cm"]
axes.name = ["X", "Y"]
axes.units_per_rev = [0.508, 0.508]
transform.type = "lapd-xy-basic"
transform.droop_correction = "None"
transform.pivot_to_center = 57.7
transform.pivot_to_clamp = 125.0
transform.zero_to_home = [10, 10]
motion_list.0.type = "grid"
motion_list.0.n = [20, 20]
motion_list.0.center = [0, 0]
motion_list.0.size = [10, 10]

